export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export type LOGIN_REQUEST = typeof LOGIN_REQUEST;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAIL = 'LOGIN_FAIL';
export type LOGIN_FAIL = typeof LOGIN_FAIL;

export const LOGOUT = 'LOGOUT';
export type LOGOUT = typeof LOGOUT;

export const UPDATE_ADMIN_REQUEST = 'UPDATE_ADMIN_REQUEST';
export type UPDATE_ADMIN_REQUEST = typeof UPDATE_ADMIN_REQUEST;

export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export type UPDATE_ADMIN_SUCCESS = typeof UPDATE_ADMIN_SUCCESS;

export const UPDATE_ADMIN_FAIL = 'UPDATE_ADMIN_FAIL';
export type UPDATE_ADMIN_FAIL = typeof UPDATE_ADMIN_FAIL;

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export type UPDATE_PASSWORD_REQUEST = typeof UPDATE_PASSWORD_REQUEST;

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export type UPDATE_PASSWORD_SUCCESS = typeof UPDATE_PASSWORD_SUCCESS;

export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export type UPDATE_PASSWORD_FAIL = typeof UPDATE_PASSWORD_FAIL;
