export const GET_FILE_LIST_REQUEST = 'GET_FILE_LIST_REQUEST';
export type GET_FILE_LIST_REQUEST = typeof GET_FILE_LIST_REQUEST;

export const GET_FILE_LIST_SUCCESS = 'GET_FILE_LIST_SUCCESS';
export type GET_FILE_LIST_SUCCESS = typeof GET_FILE_LIST_SUCCESS;

export const GET_FILE_LIST_FAIL = 'GET_FILE_LIST_FAIL';
export type GET_FILE_LIST_FAIL = typeof GET_FILE_LIST_FAIL;
