export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export type GET_TAGS_REQUEST = typeof GET_TAGS_REQUEST;

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export type GET_TAGS_SUCCESS = typeof GET_TAGS_SUCCESS;

export const GET_TAGS_FAIL = 'GET_TAGS_FAIL';
export type GET_TAGS_FAIL = typeof GET_TAGS_FAIL;

export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST';
export type GET_TYPES_REQUEST = typeof GET_TYPES_REQUEST;

export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export type GET_TYPES_SUCCESS = typeof GET_TYPES_SUCCESS;

export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';
export type GET_TYPES_FAIL = typeof GET_TYPES_FAIL;
