export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export type GET_TAGS_REQUEST = typeof GET_TAGS_REQUEST;

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export type GET_TAGS_SUCCESS = typeof GET_TAGS_SUCCESS;

export const GET_TAGS_FAIL = 'GET_TAGS_FAIL';
export type GET_TAGS_FAIL = typeof GET_TAGS_FAIL;

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export type ADD_TAG_REQUEST = typeof ADD_TAG_REQUEST;

export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export type ADD_TAG_SUCCESS = typeof ADD_TAG_SUCCESS

export const ADD_TAG_FAIL = 'ADD_TAG_FAIL';
export type ADD_TAG_FAIL = typeof ADD_TAG_FAIL;

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export type UPDATE_TAG_REQUEST = typeof UPDATE_TAG_REQUEST;

export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export type UPDATE_TAG_SUCCESS = typeof UPDATE_TAG_SUCCESS

export const UPDATE_TAG_FAIL = 'UPDATE_TAG_FAIL';
export type UPDATE_TAG_FAIL = typeof UPDATE_TAG_FAIL;

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export type DELETE_TAG_REQUEST = typeof DELETE_TAG_REQUEST;

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export type DELETE_TAG_SUCCESS = typeof DELETE_TAG_SUCCESS

export const DELETE_TAG_FAIL = 'DELETE_TAG_FAIL';
export type DELETE_TAG_FAIL = typeof DELETE_TAG_FAIL;
