// getArticleDetail
export const GET_ARTICLE_DETAIL_REQUEST = 'GET_ARTICLE_DETAIL_REQUEST';
export type GET_ARTICLE_DETAIL_REQUEST = typeof GET_ARTICLE_DETAIL_REQUEST;

export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export type GET_ARTICLE_DETAIL_SUCCESS = typeof GET_ARTICLE_DETAIL_SUCCESS;

export const GET_ARTICLE_DETAIL_FAIL = 'GET_ARTICLE_DETAIL_FAIL';
export type GET_ARTICLE_DETAIL_FAIL = typeof GET_ARTICLE_DETAIL_FAIL;

// setArticleDetail
export const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL';
export type SET_ARTICLE_DETAIL = typeof SET_ARTICLE_DETAIL;

// addArticle
export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export type ADD_ARTICLE_REQUEST = typeof ADD_ARTICLE_REQUEST;

export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export type ADD_ARTICLE_SUCCESS = typeof ADD_ARTICLE_SUCCESS;

export const ADD_ARTICLE_FAIL = 'ADD_ARTICLE_FAIL';
export type ADD_ARTICLE_FAIL = typeof ADD_ARTICLE_FAIL;

// updaterticle
export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export type UPDATE_ARTICLE_REQUEST = typeof UPDATE_ARTICLE_REQUEST;

export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export type UPDATE_ARTICLE_SUCCESS = typeof UPDATE_ARTICLE_SUCCESS;

export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';
export type UPDATE_ARTICLE_FAIL = typeof UPDATE_ARTICLE_FAIL;
