export const GET_ARTICLE_DETAIL_REQUEST = 'GET_ARTICLE_DETAIL_REQUEST';
export type GET_ARTICLE_DETAIL_REQUEST = typeof GET_ARTICLE_DETAIL_REQUEST;

export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export type GET_ARTICLE_DETAIL_SUCCESS = typeof GET_ARTICLE_DETAIL_SUCCESS;

export const GET_ARTICLE_DETAIL_FAIL = 'GET_ARTICLE_DETAIL_FAIL';
export type GET_ARTICLE_DETAIL_FAIL = typeof GET_ARTICLE_DETAIL_FAIL;

export const SET_ARTICLE_DETAIL = 'SET_ARTICLE_DETAIL';
export type SET_ARTICLE_DETAIL = typeof SET_ARTICLE_DETAIL;
