export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
export type GET_ARTICLE_LIST_REQUEST = typeof GET_ARTICLE_LIST_REQUEST;

export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export type GET_ARTICLE_LIST_SUCCESS = typeof GET_ARTICLE_LIST_SUCCESS;

export const GET_ARTICLE_LIST_FAIL = 'GET_ARTICLE_LIST_FAIL';
export type GET_ARTICLE_LIST_FAIL = typeof GET_ARTICLE_LIST_FAIL;
